spring:
  # Security OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 459442894891-s55am46n30tju7nlljhftfcl9ckipjv9.apps.googleusercontent.com
            client-secret: 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
            # redirect-url: "http://localhost:8080/oauth2/authorization/google"
            redirect-uri: "http://43.200.96.202:8080/{action}/oauth2/code/{registrationId}"
            scope: profile, email

          naver:
            client-id: Vef1Tfl3BU3SXqbU4j8O
            client-secret: gWww1FGuI9
            redirect-uri: "http://43.200.96.202:8080/{action}/oauth2/code/{registrationId}"
#            redirect-uri: "http://localhost:8080/oauth2/authorization/naver"
            authorization-grant-type: authorization_code
            scope: name, email, nickname, age, mobile
            client-name: Naver

          kakao:
            #client-id == REST api KEY
            client-id: b51941d6589770df240008eb26f02f17
            client-secret: s8eEfWkEMWwQelLdIZv2dqmEN3DwCZc6
            redirect-uri: "http://43.200.96.202:8080/oauth2/authorization/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, age_range
            client-name: Kakao

        # Provider 설정
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id