server:
  port: 8080
spring:
  profiles:
    include: oauth

  datasource:
    ## mySQL url, id, pw 설정해주세요
    # url: jdbc:mysql://strategies.cpsdhebt0ibj.ap-northeast-2.rds.amazonaws.com:3306/strategies?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
    # username: root
    # password: 3jeon-server
    url: jdbc:mysql://three-jeon-db.clhdotgui1vl.ap-northeast-2.rds.amazonaws.com:3306/three-jeon?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: threejeon1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    enabled: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace